AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 120

Metrics/LineLength:
  Max: 120

Rails/Delegate:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
